### ISSUE TITLE
console.log with "%s" doesn't print webpack stack trace

### ISSUE THREAD

**Issue by mxrlkn** [iiroj/lambda-dev#2]
Having `%s` in the console.log removes the webpack stack trace if there is any. Removing the `%s` makes it work while the log formatting remains the same (as far as I can tell).

Why `%s` doesn't work, I don't know. Can it be removed or fixed?

For example here:
https://github.com/iiroj/lambda-dev/blob/226cc3a693e0538ab0482857cddab24666712be5/lib/serve.js#L15

**Comment by iiroj** [comment]
Thanks for the bug report. I can't see any reason to keep the `%s` so might as well remove it!

**Comment by iiroj** [comment]
I just released https://github.com/iiroj/lambda-dev/commit/909106159704c92a6d724159e389de73c61dc929 with [v1.5.9](https://www.npmjs.com/package/lambda-dev).
